### ISSUE TITLE
Finalize GitOps updates

### ISSUE THREAD

**Issue by osowski** [ibm-cloud-architecture/refarch-kc-gitops#17]
- [x] Review and update Webhook Token parameters for microservice repos
  - Token has been updated and added to all microservice repos as `GITOPS_TOKEN`. Can be accessed in the GH Actions workflows via `${secrets.GITOPS_TOKEN}`.
- [x] Update GitHub Actions CI in microservice repos to check-in new app-deploy.yaml to `refarch-kc-gitops` 
  - Checkout `https://github.com/ibm-cloud-architecture/refarch-kc-gitops`
  - Replace `/services/*/base/config/app-deploy.yaml` with updated `app-deploy.yaml` from Appsody build.
  - Commit and push updates back to `refarch-kc-gitops`
  - _Create packaged GitHub Action as needed_
- [x] Create new `eda-integration` environment and document the flow for root `README.md`
  - Based off of `example-credentials`
  - However, for now this assumes definition of secrets inside the namespace/project already
- [x] Merge SCRAM support into upstream microservices
  - PRs for `KAFKA_USER` and `KAFKA_PASSWORD` have been merged into upstream microservices successfully and verified in the 2020.05 cluster's `eda-integration` environment.
- [x] Merge SCRAM support updates from upstream microservices
  - Update `/services/*/overlays/*.yaml` as needed
  - Comment out necessary components from `/env/base/kustomization.yaml`
- [x] Create new ArgoCD deployments in 2020.08 cluster, targeting new `eda-integration` environment

**Comment by osowski** [comment]
Updated original comment above - Token has been updated and added to all microservice repos as `GITOPS_TOKEN`. Can be accessed in the GH Actions workflows via `${secrets.GITOPS_TOKEN}`.

**Comment by osowski** [comment]
Merged @jesusmah SCRAM updates into `services` via https://github.com/ibm-cloud-architecture/refarch-kc-gitops/pull/16

**Comment by osowski** [comment]
Pending `environment/eda-integration-2020.08` implementation available via https://github.com/osowski/refarch-kc-gitops/tree/master/environments/eda-integration-2020.08

**Comment by osowski** [comment]
Initial `eda-integration-2020.08` environment merged in via https://github.com/ibm-cloud-architecture/refarch-kc-gitops/pull/18

**Comment by djones6** [comment]
GitHub actions CI updates:
- [x] `refarch-kc-ms`: Done (https://github.com/ibm-cloud-architecture/refarch-kc-ms/pull/64)
- [ ] `refarch-kc-order-ms`:
- [ ] `refarch-kc-container-ms`:
- [ ] `refarch-kc-ui`:
- [ ] `refarch-reefer-ml`:

**Comment by osowski** [comment]
There appears to be an issue with the version of kustomize that ships with the current ArgoCD versions (included in the operator) and it manifests when trying to use a folder structure like the one we have implemented. 

Reference: https://github.com/kubernetes-sigs/kustomize/issues/2538

We can specify custom versions of kustomize [Link 1](https://argoproj.github.io/argo-cd/user-guide/kustomize/) & [Link 2](https://argoproj.github.io/argo-cd/operator-manual/custom_tools/), however I am unsure of how this would get rolled into the ArgoCD deployment we have since it is managed by the ArgoCD operator. 

The [Repo Server](https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#repo-options) component is where the specific kustomize binaries need to live, but the operator spec does not currently detail the availability to support the modifications needed by the core ArgoCD documentation.

I will investigate more upon my return on Monday, 8/24. 

ArgoCD Application YAML:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: KContainer All In One
spec:
  destination:
    namespace: eda-integration
    server: 'https://kubernetes.default.svc'
  source:
    path: environments/eda-integration-2020.08/
    repoURL: 'https://github.com/ibm-cloud-architecture/refarch-kc-gitops'
    targetRevision: HEAD
  project: eda-integration
```

**Comment by osowski** [comment]
Surprisingly, a typo (or leftover namespace in one of the app-deploy.yaml files) was throwing a red herring error message. Removing the `namespace: shipping` from the `order-query-ms/base/config/app-deploy.yaml` allowed the environment to be deployed with all the default versions of ArgoCD and Kustomize. 

Some additional investigation discovered that we're going to need to complete https://github.ibm.com/case/gse-eda/issues/105 to adopt the new naming structure I had originally implemented this environment, as the POSTGRES credentials are a part of the base app-deploy.yaml and not any kustomizations. I will work on that later this week, but that does not affect the completion of this item being successfully deployed!

**Comment by osowski** [comment]
I consolidated the POSTGRES secrets and redeployed using this process and everything worked great. Verified the environment is up and running via an `itg-tests` run and everything went smoothly!

Now on to the documentation!

**Comment by djones6** [comment]
Awesome!
